version: '3.7'

services:
  app:
    build:
      args:
        USER: ${USER}
        UID: ${UID}
        PHP_VERSION: ${PHP_VERSION}
      context: ./
      dockerfile: ./docker-config/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes: 
    - ./app:/var/www
    networks: 
    - lemp-stack

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports: 
      - $EXPOSED_PORT:80
    volumes:
      - ./app:/var/www
      - ./docker-config/nginx/default-conf:/etc/nginx/conf.d
    networks:
     - lemp-stack

  mariadb:
    image: mariadb:10.5.2
    restart: unless-stopped
    volumes:  
      - ./data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks: 
      - lemp-stack

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
      - ${PHPMA_PORT}:80
    depends_on: 
      - mariadb
    networks: 
      - lemp-stack

networks:
  lemp-stack:
    driver: bridge
  


